# Generated by Django 4.2.6 on 2023-11-17 18:35

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", markdownx.models.MarkdownxField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views", models.IntegerField(default="0")),
                ("image", models.ImageField(null=True, upload_to="uploads/")),
            ],
        ),
    ]
