# Generated by Django 4.2.6 on 2023-11-17 03:27

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_created_at_alter_post_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
